name = "HierarchicalEOM"
uuid = "a62dbcb7-80f5-4d31-9a88-8b19fd92b128"
authors = ["Yi-Te Huang <y.t.d.huang@phys.ncku.edu.tw>"]
version = "1.5.3"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
FastExpm = "7868e603-8603-432e-a1a1-694bd70b01f2"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLOperators = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[extensions]
HierarchicalEOM_CUDAExt = "CUDA"
HierarchicalEOM_QuantumOpticsExt = "QuantumOptics"
HierarchicalEOM_QuantumToolboxExt = "QuantumToolbox"

[compat]
CUDA = "5"
DiffEqCallbacks = "2, 3"
FastExpm = "1.1.0"
JLD2 = "0.4.31"
LinearAlgebra = "<0.0.1, 1"
LinearSolve = "2.4.2"
OrdinaryDiffEq = "6.53.4"
Pkg = "<0.0.1, 1"
PrecompileTools = "1"
ProgressMeter = "1.7"
QuantumOptics = "1"
QuantumToolbox = "0"
Reexport = "1"
SciMLOperators = "0.3.5"
SparseArrays = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
