name: Documenter

on:
  push:
    branches:
      - 'main'
    tags: 
      - '*'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/documentation.yml'
      - 'src/**'
      - 'ext/**'
      - 'docs/**'
      - 'examples/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    permissions: # needed to allow julia-actions/cache to delete old caches that it has created
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - name: Install Julia Package dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ --color=yes --code-coverage=user docs/make.jl
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}